### ISSUE TITLE
Chatwoot 3.0 errors with Evolution-API

### ISSUE THREAD

**Issue by uhlhosting** [figurolatam/chatwoot-sdk#5]
Hi, using latest release inside Evolution-API, and I get: with latest chatwoot 3.0

```
 [Evolution API]  v1.5.0  1   -  Sat Sep 16 2023 08:23:34     ERROR   [unhandledRejection]  [object]   
2023-09-16T11:23:34.873574788Z {
2023-09-16T11:23:34.873598099Z   origin: Promise {
2023-09-16T11:23:34.873602702Z     <rejected> ApiError: Internal Server Error
2023-09-16T11:23:34.873606602Z         at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
2023-09-16T11:23:34.873610233Z         at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
2023-09-16T11:23:34.873614015Z         at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2023-09-16T11:23:34.873617544Z       url: 'https://chat-web.uhl.cloud/api/v1/accounts/2/conversations',
2023-09-16T11:23:34.873621435Z       status: 500,
2023-09-16T11:23:34.873636555Z       statusText: 'Internal Server Error',
2023-09-16T11:23:34.873640867Z       body: [Object],
2023-09-16T11:23:34.873643956Z       request: [Object]
2023-09-16T11:23:34.873646978Z     }
2023-09-16T11:23:34.873649973Z   },
2023-09-16T11:23:34.873653046Z   stderr: 2,
2023-09-16T11:23:34.873656216Z   error: ApiError: Internal Server Error
2023-09-16T11:23:34.873659336Z       at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
2023-09-16T11:23:34.873662658Z       at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
2023-09-16T11:23:34.873665981Z       at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2023-09-16T11:23:34.873669662Z     url: 'https://chat-web.uhl.cloud/api/v1/accounts/2/conversations',
2023-09-16T11:23:34.873673016Z     status: 500,
2023-09-16T11:23:34.873676797Z     statusText: 'Internal Server Error',
2023-09-16T11:23:34.873680615Z     body: { status: 500, error: 'Internal Server Error' },
2023-09-16T11:23:34.873683693Z     request: {
2023-09-16T11:23:34.873686762Z       method: 'POST',
2023-09-16T11:23:34.873689767Z       url: '/api/v1/accounts/{account_id}/conversations',
2023-09-16T11:23:34.873692721Z       path: [Object],
2023-09-16T11:23:34.873695791Z       body: [Object],
2023-09-16T11:23:34.873698800Z       errors: [Object]
2023-09-16T11:23:34.873701869Z     }
2023-09-16T11:23:34.873705055Z   }
2023-09-16T11:23:34.873708150Z } 
2023-09-16T11:23:34.873711288Z 
2023-09-16T11:24:29.819266225Z [Evolution API]  v1.5.0  1   -  Sat Sep 16 2023 08:24:29     

```

linked to: https://github.com/EvolutionAPI/evolution-api/issues/114

**Comment by neguimzoiverde** [comment]
I have the same problem! It always happens when I try to create a new instance in chatwoot, linking the Evolution-API to it.

**Comment by tiagocordeiro** [comment]
I have the same problem, but it only occurs when `account_id` is not equal to 1.
